// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Session struct {
	TrackerID     int64
	StartDatetime string
	EndDatetime   sql.NullString
	Note          sql.NullString
}

type Tracker struct {
	ID   int64
	Name string
}
