// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trackers.sql

package database

import (
	"context"
)

const getTrackers = `-- name: GetTrackers :many
select id, name from trackers
`

func (q *Queries) GetTrackers(ctx context.Context) ([]Tracker, error) {
	rows, err := q.db.QueryContext(ctx, getTrackers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tracker
	for rows.Next() {
		var i Tracker
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
